spring:
  application:
    name: locadora_rdt_backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

security:
    oauth2:
      client:
        client-id: ${OAUTH_CLIENT_ID}
        client-secret: ${OAUTH_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  duration: 86400
